---
title: "testing"
format: html
editor: visual
---

```{r}
library(tidyverse)
```


```{r}
dir <- substr(getwd(), 1,2)

path <- ifelse(dir == "C:", 
               "P:/41001581_egenutvikling_anders_kolstad/data/",
               "/data/Egenutvikling/41001581_egenutvikling_anders_kolstad/data/")
naturtyper <- readRDS(paste0(path, "naturtyper.rds"))
```

```{r}
 summary1 <- naturtyper %>%
    group_by(tilstand) %>%
    summarise(Antall_lokaliteter = n(),
              Areal_km2 = round(sum(km2), 0))
```

```{r}
ggplot(summary1, aes(x = tilstand, y = Antall_lokaliteter))+
      geom_bar(stat="identity",
               fill = "grey80",
               colour = "grey20",
               linewidth=1.5)+
      theme_bw(base_size = 12)
```


```{r}
myvar <- rlang::sym("tilstand")

summary2 <- naturtyper %>%
    group_by(myVar = !!myvar) %>%
    summarise(Antall_lokaliteter = n(),
              Areal_km2 = round(sum(km2), 0))
class(summary2)
```

```{r}
ggplot(summary2, aes_string(x = "myVar", y = "Antall_lokaliteter"))+
      geom_bar(stat="identity",
               fill = "grey80",
               colour = "grey20",
               linewidth=1.5)+
      theme_bw(base_size = 12)
```

```{r}
naturtyper %>%
      filter(naturtype == "Naturbeitemark") %>%
      group_by(kartleggingsår) %>%
      summarise(Antall_lokaliteter = n(),
                Areal_km2 = round(sum(km2), 0)) 
```

```{r}
temp <- dat2_long %>% filter(naturtype == "Naturbeitemark") %>%
  group_by(NiN_variable_code, NiN_variable_value) %>%
      summarise(Antall_lokaliteter = n(),
                Areal_km2 = round(sum(km2), 0))

ggplot(temp, aes(x = NiN_variable_value, y = Antall_lokaliteter))+
  geom_bar(stat="identity",
               fill = "#FF9933",
               colour = "grey20",
               linewidth=1.5)+
      theme_bw(base_size = 12)+
  facet_wrap(.~NiN_variable_code,
             scales = "free",
             ncol = 3)
```


```{r}
ggplot(temp[temp$NiN_variable_code=="PRHA",], aes(x = NiN_variable_value, y = Antall_lokaliteter))+
  geom_bar(stat="identity",
               fill = "#FF9933",
               colour = "grey20",
               linewidth=1.5)+
      theme_bw(base_size = 12)
```


```{r}
temp2 <- temp %>%
  group_by(tilstand) %>%
  summarise(n = n())
```

```{r}
ggplot(temp, aes(x = tilstand, y = n))+
  geom_bar(stat = "identity")
```



```{r}
cond <- TRUE
naturtyper_long_selected_var <- 
   naturtyper_long %>% 
     filter(naturtype == "Naturbeitemark") %>%
     filter(NiN_variable_code == "PRRL-EN") %>%
     group_by(NiN_variable_code, NiN_variable_value) %>%
     { if (cond) group_by(., kartleggingsår, .add=T) else . } %>%
     summarise(Antall_lokaliteter = n(),
               Areal_km2 = round(sum(km2), 0))
```

```{r}
ggplot(naturtyper_long_selected_var, aes(x = NiN_variable_value, y = Antall_lokaliteter))+
    geom_bar(stat="identity",
             fill = "#FF9933",
             colour = "grey20",
             linewidth=1.5)+
    theme_bw(base_size = myBase_size) +
  facet_grid(vars(kartleggingsår))
```

```{r}
x1 <- "kartleggingsår"
x2 <- "7FA"
```


```{r}
temp <- naturtyper_long %>%
  filter(naturtype == "Naturbeitemark") %>%
  { if( !x1 %in% varList2) {
     filter(., NiN_variable_code == x2) %>%
     pivot_wider(., id_cols = identifikasjon_lokalid,
                                       names_from = NiN_variable_code,
                                       values_from = NiN_variable_value)
  } else { select(., identifikasjon_lokalid, km2, x1) %>%
      distinct(., identifikasjon_lokalid, .keep_all = T)}}


temp2 <- naturtyper_long %>%
  filter(naturtype == "Naturbeitemark") %>%
  { if( !x2 %in% varList2) {
     filter(., NiN_variable_code == x2) %>%
     pivot_wider(., id_cols = identifikasjon_lokalid,
                                       names_from = NiN_variable_code,
                                       values_from = NiN_variable_value)
  } else { select(., identifikasjon_lokalid, x1) %>%
      distinct(., identifikasjon_lokalid) }}

temp_out <- full_join(temp, temp2, by = "identifikasjon_lokalid")
temp_out <- temp_out %>%
  rename("first_variable" = 3,
         "second_variable" = 4)

temp_out <- temp_out %>%
  group_by(first_variable, second_variable) %>%
  summarise(Antall_lokaliteter = n(),
            Areal_km2 = round(sum(km2), 0))

```



```{r}
ggplot(temp_out, aes(x = first_variable, y = Antall_lokaliteter))+
    geom_bar(stat="identity",
             fill = "#FFCC99",
             colour = "grey20",
             linewidth=1.5)+
    theme_bw(base_size = 20) +
  facet_wrap(.~second_variable)
```


```{r}
tempdat <- naturtyper_long %>%
  filter(naturtype == "Naturbeitemark")

x1 <- "kartleggingsår"
x2 <- "7FA"
x1 <- x2
x2 <-  "Ingen"
x2 <-  "tilstand"

km <- select(naturtyper, identifikasjon_lokalid, km2)
```



```{r}
temp <- tempdat %>%
     { if( !x1 %in% varList2) {
       filter(., NiN_variable_code == x1) %>%
         pivot_wider(., id_cols = identifikasjon_lokalid,
                     names_from = NiN_variable_code,
                     values_from = NiN_variable_value) %>%
         full_join(select(naturtyper, identifikasjon_lokalid, km2),
                   by = "identifikasjon_lokalid") %>%
         select(identifikasjon_lokalid, km2, 2)
       } else { select(., identifikasjon_lokalid, km2, x1) %>%
         distinct(., identifikasjon_lokalid, .keep_all = T)}}
   
    if(x2 != "Ingen") {
     temp2 <- tempdat %>%
       { if( !x2 %in% varList2) {
         filter(., NiN_variable_code == x2) %>%
           pivot_wider(., id_cols = identifikasjon_lokalid,
                       names_from = NiN_variable_code,
                       values_from = NiN_variable_value)
       } else { select(., identifikasjon_lokalid, x2) %>%
           distinct(., identifikasjon_lokalid, .keep_all = T) }} %>%
       full_join(temp, by = "identifikasjon_lokalid") %>%
       rename("second_variable" = 2,
              "first_variable" = 4)
    } else {temp2 <- temp %>%
    rename("first_variable" = 3)}
     
   temp_out <- temp2 %>%
     group_by(first_variable) %>%
     {if (x2 != "Ingen") group_by(., second_variable, .add=T) else . } %>%
     summarise(
       Antall_lokaliteter = n(),
       Areal_km2 = round(sum(km2), 0))
```



```{r}
get_code <- naturtyper %>%
  filter(grepl("ntyp", naturtypekode)) %>%
  distinct(naturtype, .keep_all = T) %>%
  mutate(naturtypekode_short = str_remove(naturtypekode, "ntyp_")) %>%
  select(naturtypekode_short, naturtype)

naturtyper <- naturtyper %>%
  left_join(get_code, by = "naturtype") %>%
  mutate(naturtype = paste(naturtypekode_short, naturtype))


sort(unique(naturtyper$naturtype))
```













